services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: quadros_e_circulos_api
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: quadros_e_circulos_api_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # Porta 5433 no host mapeada para 5432 do container

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
    ports:
      - "3001:3000"  # Porta 3001 no host mapeada para 3000 do container
    depends_on:
      - db
    environment:
      # Dentro da rede Docker, o serviço db ainda escuta na 5432
      DATABASE_URL: postgres://quadros_e_circulos_api:${POSTGRES_PASSWORD}@db:5432/quadros_e_circulos_api_development
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5

volumes:
  pgdata:
