openapi: 3.0.3
info:
  title: Frames API
  version: 1.0.0
  description: API para criar frames com círculos, garantindo que os círculos não se sobreponham e também checando sobreposição entre frames.

servers:
  - url: http://localhost:3000
    description: Servidor local de desenvolvimento

paths:
  /frames:
    post:
      summary: Cria um novo frame com círculos opcionais
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FrameCreateRequest"
            examples:
              frame-sem-circulos:
                summary: Frame sem círculos (persiste)
                value:
                  frame:
                    center_x: 300.0
                    center_y: 300.0
                    width: 400.0
                    height: 400.0

              frame-com-circulos-sobrepostos:
                summary: Frame com círculos sobrepostos (não persiste)
                value:
                  frame:
                    center_x: 800.0
                    center_y: 300.0
                    width: 400.0
                    height: 400.0
                    circles:
                      - center_x: 750.0
                        center_y: 300.0
                        radius: 50.0
                      - center_x: 790.0
                        center_y: 300.0
                        radius: 50.0

              frame-com-circulos-sem-sobreposicao:
                summary: Frame com círculos sem sobreposição (persiste)
                value:
                  frame:
                    center_x: 900.0
                    center_y: 300.0
                    width: 400.0
                    height: 400.0
                    circles:
                      - center_x: 820.0
                        center_y: 220.0
                        radius: 50.0
                      - center_x: 980.0
                        center_y: 220.0
                        radius: 50.0
                      - center_x: 900.0
                        center_y: 380.0
                        radius: 40.0

              frame-com-sobreposicao-com-outro-frame:
                summary: Frame com sobreposição a outro frame (não persiste)
                value:
                  frame:
                    center_x: 500.0
                    center_y: 300.0
                    width: 400.0
                    height: 400.0
                    circles: []

      responses:
        "201":
          description: Frame criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FrameResponse"
              examples:
                sucesso:
                  value:
                    id: 1
                    center_x: 300.0
                    center_y: 300.0
                    width: 400.0
                    height: 400.0
                    circles: []

        "422":
          description: Erro de validação — círculos se sobrepõem ou frames com sobreposição
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                overlap_error_circles:
                  value:
                    errors:
                      - "Circle at (750.0, 300.0) overlaps with one at (790.0, 300.0)"
                overlap_error_frames:
                  value:
                    errors:
                      - "must not touch or intersect another frame"
                invalid_data:
                  value:
                    errors:
                      - "Width can't be blank"

  /frames/{frame_id}/circles:
    post:
      summary: Adiciona um círculo ao quadro especificado
      parameters:
        - name: frame_id
          in: path
          description: ID do frame ao qual o círculo será adicionado
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CircleCreateRequest"
            examples:
              circulo-sem-sobreposicao:
                summary: Círculo sem sobreposição no frame (persiste)
                value:
                  circle:
                    center_x: 350.0
                    center_y: 350.0
                    radius: 50.0

              circulo-com-sobreposicao:
                summary: Círculo com sobreposição no frame (não persiste)
                value:
                  circle:
                    center_x: 310.0
                    center_y: 300.0
                    radius: 100.0

      responses:
        "201":
          description: Círculo criado com sucesso no frame
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Circle"
              examples:
                sucesso:
                  value:
                    id: 10
                    center_x: 350.0
                    center_y: 350.0
                    radius: 50.0
                    frame_id: 1

        "404":
          description: Frame não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                frame_nao_encontrado:
                  value:
                    errors:
                      - "Frame not found"

        "422":
          description: Erro de validação — círculo com sobreposição ou dados inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                overlap_error_circle:
                  value:
                    errors:
                      - "overlaps with an existing circle in this frame"
                invalid_data:
                  value:
                    errors:
                      - "Center x can't be blank"

  /circles/{id}:
    put:
      summary: Atualiza a posição de um círculo existente
      parameters:
        - name: id
          in: path
          description: ID do círculo a ser atualizado
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CircleCreateRequest"
            examples:
              circulo-sem-sobreposicao:
                summary: Atualização válida de círculo sem sobreposição (persiste)
                value:
                  circle:
                    center_x: 1250.0
                    center_y: 300.0
                    radius: 50.0
              circulo-com-sobreposicao:
                summary: Atualização de círculo com sobreposição (não persiste)
                value:
                  circle:
                    center_x: 1350.0
                    center_y: 300.0
                    radius: 50.0

      responses:
        "200":
          description: Círculo atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Circle"
              examples:
                sucesso:
                  value:
                    id: 20
                    center_x: 1250.0
                    center_y: 300.0
                    radius: 50.0
                    frame_id: 3

        "404":
          description: Círculo não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                circle_nao_encontrado:
                  value:
                    errors:
                      - "Circle not found"

        "422":
          description: Erro de validação — círculo com sobreposição ou dados inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                overlap_error_circle:
                  value:
                    errors:
                      - "overlaps with an existing circle in this frame"
                invalid_data:
                  value:
                    errors:
                      - "Center x can't be blank"

  /circles:
    get:
      summary: Lista todos os círculos completamente dentro do raio especificado a partir de um ponto central, opcionalmente filtrados por quadro
      parameters:
        - name: center_x
          in: query
          description: Coordenada X do ponto central
          required: true
          schema:
            type: number
            format: float
        - name: center_y
          in: query
          description: Coordenada Y do ponto central
          required: true
          schema:
            type: number
            format: float
        - name: radius
          in: query
          description: Raio do círculo de busca (centímetros)
          required: true
          schema:
            type: number
            format: float
        - name: frame_id
          in: query
          description: ID do frame para filtrar círculos (opcional)
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Lista de círculos dentro do raio especificado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Circle"
              examples:
                sem_filtro:
                  summary: Retorna círculos dentro do raio sem filtro de frame
                  value:
                    - id: 1
                      center_x: 100.0
                      center_y: 150.0
                      radius: 50.0
                      frame_id: 1
                    - id: 2
                      center_x: 200.0
                      center_y: 200.0
                      radius: 30.0
                      frame_id: 1

                com_filtro:
                  summary: Retorna círculos dentro do raio filtrando por frame_id
                  value:
                    - id: 10
                      center_x: 1010.0
                      center_y: 1010.0
                      radius: 20.0
                      frame_id: 3

        "422":
          description: Erro de validação — parâmetros obrigatórios faltando ou inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                missing_params:
                  value:
                    errors:
                      - "center_x, center_y and radius are required"

  /frames/{id}:
    get:
      summary: Retorna detalhes de um quadro com métricas dos círculos
      parameters:
        - name: id
          in: path
          description: ID do frame a ser retornado
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Detalhes do frame com métricas dos círculos
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  center_x:
                    type: number
                    example: 300.0
                  center_y:
                    type: number
                    example: 300.0
                  width:
                    type: number
                    example: 400.0
                  height:
                    type: number
                    example: 400.0
                  total_circles:
                    type: integer
                    example: 3
                  circle_top:
                    type: object
                    nullable: true
                    properties:
                      center_x:
                        type: number
                        example: 300.0
                      center_y:
                        type: number
                        example: 260.0
                      radius:
                        type: number
                        example: 40.0
                  circle_bottom:
                    type: object
                    nullable: true
                    properties:
                      center_x:
                        type: number
                        example: 300.0
                      center_y:
                        type: number
                        example: 340.0
                      radius:
                        type: number
                        example: 40.0
                  circle_left:
                    type: object
                    nullable: true
                    properties:
                      center_x:
                        type: number
                        example: 260.0
                      center_y:
                        type: number
                        example: 300.0
                      radius:
                        type: number
                        example: 40.0
                  circle_right:
                    type: object
                    nullable: true
                    properties:
                      center_x:
                        type: number
                        example: 340.0
                      center_y:
                        type: number
                        example: 300.0
                      radius:
                        type: number
                        example: 40.0

      examples:
        sucesso:
          value:
            id: 2
            center_x: 1300.0
            center_y: 300.0
            width: 400.0
            height: 400.0
            total_circles: 3
            circle_top:
              center_x: 1300.0
              center_y: 260.0
              radius: 40.0
            circle_bottom:
              center_x: 1300.0
              center_y: 340.0
              radius: 40.0
            circle_left:
              center_x: 1260.0
              center_y: 300.0
              radius: 40.0
            circle_right:
              center_x: 1340.0
              center_y: 300.0
              radius: 40.0

  /circles/{id}:
    delete:
      summary: Remove um círculo pelo ID
      parameters:
        - name: id
          in: path
          description: ID do círculo a ser removido
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Círculo removido com sucesso (sem conteúdo)
        "404":
          description: Círculo não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                circle_nao_encontrado:
                  value:
                    errors:
                      - "Circle not found"


components:
  schemas:
    FrameCreateRequest:
      type: object
      properties:
        frame:
          $ref: '#/components/schemas/Frame'
      required:
        - frame

    FrameResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Frame'
      properties:
        id:
          type: integer
        circles:
          type: array
          items:
            $ref: '#/components/schemas/Circle'

    Frame:
      type: object
      properties:
        center_x:
          type: number
          format: float
        center_y:
          type: number
          format: float
        width:
          type: number
          format: float
        height:
          type: number
          format: float
      required:
        - center_x
        - center_y
        - width
        - height

    CircleCreateRequest:
      type: object
      properties:
        circle:
          $ref: '#/components/schemas/Circle'
      required:
        - circle

    Circle:
      type: object
      properties:
        id:
          type: integer
        center_x:
          type: number
          format: float
        center_y:
          type: number
          format: float
        radius:
          type: number
          format: float
        frame_id:
          type: integer
      required:
        - center_x
        - center_y
        - radius

    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
